import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

EXCLUDE = {"Preah Khan Reach ...", "Sancaktepe ...", "Beşiktaş JK Altyapi", "Bakirkoy Kadin ..."}

raw = json.loads((ROOT / "data/raw/TUR1_players.json").read_text(encoding="utf-8"))
raw_clean = [p for p in raw if p.get("club") not in EXCLUDE]
(ROOT / "data/raw/TUR1_players.json").write_text(json.dumps(raw_clean, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Raw: {len(raw)} → {len(raw_clean)}")

app = json.loads((ROOT / "data/players_app.json").read_text(encoding="utf-8"))
app_clean = [p for p in app if p.get("club") not in EXCLUDE]
for i, p in enumerate(app_clean):
    p["id"] = i + 1
(ROOT / "data/players_app.json").write_text(json.dumps(app_clean, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"App: {len(app)} → {len(app_clean)}")

leagues = sorted(set(p["league"] for p in app_clean))
countries = sorted(set(p["nationality"] for p in app_clean if p["nationality"]))
ts = (
    "// AUTO-GENERATED by scraper/soccerdonna_scraper.py — do not edit manually\n\n"
    'import type { Player } from "@/types";\n\n'
    "export const PLAYERS: Player[] = \n"
    + json.dumps(app_clean, ensure_ascii=False, indent=2)
    + ";\n\n"
    f"export const TOTAL_PLAYERS = {len(app_clean)};\n"
    f"export const LEAGUES = {json.dumps(leagues, ensure_ascii=False)};\n"
    f"export const COUNTRIES = {json.dumps(countries, ensure_ascii=False)};\n"
)
(ROOT / "src/data/players.ts").write_text(ts, encoding="utf-8")
print(f"TypeScript yazıldı → {len(app_clean)} oyuncu")

clubs = sorted(set(p["club"] for p in app_clean))
print(f"\nTakımlar ({len(clubs)}):")
for c in clubs:
    cnt = sum(1 for p in app_clean if p["club"] == c)
    print(f"  {cnt:3d}  {c}")
