"""
HerGame — JSON → Web App Converter
====================================
Converts the scraped players_all.json into two formats:

  1. data/players_app.json   — clean JSON for the Next.js API route
  2. data/players_app.ts     — TypeScript const for direct import

The output matches the Player interface in types/index.ts.

Usage:
  python json_to_app.py
  python json_to_app.py --input data/players_all.json --min-value 0
"""

import argparse
import json
import re
import sys
from pathlib import Path


# ── Helpers ───────────────────────────────────────────────────────────────────
def clean_name(name: str) -> str:
    return re.sub(r"\s+", " ", name).strip()


def parse_market_value_display(raw: str, num: float) -> str:
    """Produce display string like €2.5M or €300K from raw or numeric."""
    if num >= 1_000_000:
        return f"€{num / 1_000_000:.1f}M"
    if num >= 1_000:
        return f"€{num / 1_000:.0f}K"
    if raw:
        return raw
    return "N/A"


def normalise_position(pos: str) -> str:
    pos = pos.upper().strip()
    if pos in ("GK", "DF", "MF", "FW"):
        return pos
    return "MF"  # fallback


def safe_int(val) -> int:
    try:
        return int(val) if val is not None else 0
    except (ValueError, TypeError):
        return 0


NATIONALITY_TO_SHORT = {
    "England": "England", "Scotland": "Scotland", "Wales": "Wales",
    "United States": "USA", "USA": "USA",
    "Turkey": "Turkey", "Spain": "Spain", "Germany": "Germany",
    "France": "France", "Brazil": "Brazil", "Norway": "Norway",
    "Sweden": "Sweden", "Denmark": "Denmark", "Netherlands": "Netherlands",
    "Australia": "Australia", "Nigeria": "Nigeria", "Chile": "Chile",
    "Poland": "Poland", "Portugal": "Portugal", "Italy": "Italy",
    "Canada": "Canada", "Japan": "Japan",
}

COUNTRY_FLAGS = {
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "Turkey": "🇹🇷", "Spain": "🇪🇸", "Germany": "🇩🇪", "France": "🇫🇷",
    "USA": "🇺🇸", "Brazil": "🇧🇷", "Norway": "🇳🇴", "Sweden": "🇸🇪",
    "Denmark": "🇩🇰", "Netherlands": "🇳🇱", "Australia": "🇦🇺",
    "Nigeria": "🇳🇬", "Chile": "🇨🇱", "Poland": "🇵🇱", "Portugal": "🇵🇹",
    "Italy": "🇮🇹", "Canada": "🇨🇦", "Japan": "🇯🇵",
}


def transform_player(raw: dict, idx: int) -> dict:
    """Transform raw scraped dict to web app format."""
    name = clean_name(raw.get("name") or raw.get("full_name") or "Unknown")
    nationality = NATIONALITY_TO_SHORT.get(
        raw.get("nationality", ""), raw.get("nationality", "")
    )
    flag = raw.get("flag") or COUNTRY_FLAGS.get(nationality, "🌍")
    mv_num = float(raw.get("market_value_num") or 0)
    mv_display = parse_market_value_display(raw.get("market_value", ""), mv_num)

    transfers = raw.get("transfers") or []
    if not isinstance(transfers, list):
        transfers = []

    achievements = raw.get("achievements") or []
    if not isinstance(achievements, list):
        achievements = []

    return {
        "id": idx + 1,
        "soccerdonna_id": raw.get("id") or str(idx + 1),
        "soccerdonna_url": raw.get("soccerdonna_url", ""),
        "name": name,
        "age": safe_int(raw.get("age")),
        "born": raw.get("born") or "",
        "birth_place": raw.get("birth_place") or "",
        "nationality": nationality,
        "flag": flag,
        "club": raw.get("club") or "",
        "league": raw.get("league") or "",
        "league_code": raw.get("league_code") or "",
        "position": normalise_position(raw.get("position") or "MF"),
        "position_detail": raw.get("position_detail") or "",
        "height": raw.get("height") or "",
        "foot": raw.get("foot") or "",
        "goals": safe_int(raw.get("goals")),
        "assists": safe_int(raw.get("assists")),
        "appearances": safe_int(raw.get("appearances")),
        "caps": safe_int(raw.get("caps")),
        "national_team": raw.get("national_team") or nationality,
        "national_goals": safe_int(raw.get("national_goals")),
        "yellow_cards": safe_int(raw.get("yellow_cards")),
        "red_cards": safe_int(raw.get("red_cards")),
        "market_value": mv_display,
        "market_value_num": mv_num,
        "photo_url": raw.get("photo_url") or "",
        "bio": raw.get("bio") or "",
        "transfers": transfers,
        "achievements": achievements,
    }


def players_to_typescript(players: list[dict]) -> str:
    """Generate TypeScript file with typed player array."""
    ts_lines = [
        "// AUTO-GENERATED by json_to_app.py — do not edit manually",
        "// Re-run: python scraper/json_to_app.py",
        "",
        'import type { Player } from "@/types";',
        "",
        "export const PLAYERS: Player[] = ",
        json.dumps(players, ensure_ascii=False, indent=2),
        ";",
        "",
        f"export const TOTAL_PLAYERS = {len(players)};",
        f"export const LEAGUES = {json.dumps(sorted(set(p['league'] for p in players)), ensure_ascii=False)};",
        f"export const COUNTRIES = {json.dumps(sorted(set(p['nationality'] for p in players if p['nationality'])), ensure_ascii=False)};",
    ]
    return "\n".join(ts_lines)


def main():
    parser = argparse.ArgumentParser(description="Convert scraped JSON to web app format")
    parser.add_argument("--input", default="data/players_all.json")
    parser.add_argument("--out-json", default="data/players_app.json")
    parser.add_argument("--out-ts", default="../src/data/players.ts")
    parser.add_argument("--min-apps", type=int, default=0,
                        help="Minimum appearances to include (filter out very sparse profiles)")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"❌ Input file not found: {args.input}")
        print("   Run soccerdonna_scraper.py first.")
        sys.exit(1)

    with open(input_path, encoding="utf-8") as f:
        raw_players = json.load(f)

    print(f"Loaded {len(raw_players)} raw players from {args.input}")

    # Filter and transform
    transformed = []
    skipped = 0
    for i, raw in enumerate(raw_players):
        if not raw.get("name"):
            skipped += 1
            continue
        if safe_int(raw.get("appearances")) < args.min_apps and args.min_apps > 0:
            skipped += 1
            continue
        transformed.append(transform_player(raw, len(transformed)))

    print(f"Transformed: {len(transformed)} players (skipped {skipped})")

    # Save JSON
    out_json = Path(args.out_json)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(transformed, f, ensure_ascii=False, indent=2)
    print(f"✅ JSON saved → {out_json}")

    # Save TypeScript
    out_ts = Path(args.out_ts)
    out_ts.parent.mkdir(parents=True, exist_ok=True)
    with open(out_ts, "w", encoding="utf-8") as f:
        f.write(players_to_typescript(transformed))
    print(f"✅ TypeScript saved → {out_ts}")

    # Print summary
    leagues = {}
    for p in transformed:
        lg = p["league"]
        leagues[lg] = leagues.get(lg, 0) + 1
    print("\n📊 Players per league:")
    for lg, cnt in sorted(leagues.items(), key=lambda x: -x[1]):
        print(f"   {cnt:3d}  {lg}")


if __name__ == "__main__":
    main()
